{
    "name": "Advanced Credit Limit Management | Cuenta Corriente",
    "version": "19.0.1.1.0",
    "author": "Tecnegia",
    "summary": "Gestión avanzada de Límite de Crédito, Cuentas Corrientes y Riesgo Crediticio",
    "description": "Control preventivo de deuda, límites de crédito, seguimiento de pagos y gestión de riesgo crediticio para clientes. Palabras clave: Cuenta Corriente, Límite de Crédito, Riesgo, Cobranzas, Mora, Credit Limit.",
    "category": "Contact",
    "depends": [
        "base",
        "account",
        "sale",
        "sale_management",
        "l10n_latam_check",
    ],

    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "wizard/credit_account_change_view.xml",
        "wizard/upload_credit_document_view.xml",
        "views/credit_limit_fields.xml",
        "views/res_config_settings_view.xml",
        "views/account_move.xml",
        "views/account_payment_term.xml",
        "views/sale_order_view.xml",
    ],
    "installable": True,
    "auto_install": False,
    "license": "OPL-1",
    "price": 149.00,
    "currency": "EUR",
    "images": ["static/description/banner.png"],
}
